// BatQAM - draw a batman (or other) logo with 2 x DAC's fed by DMA
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/timer.h>
#include <libopencm3/cm3/nvic.h>
#include <libopencm3/stm32/dac.h>
#include <libopencm3/stm32/dma.h>
// Globals - provided in the header file, auto-generated by python
#include "bat.h"
// Timer 2 count period, 16 microseconds for a 72MHz APB2 clock
#define PERIOD 1152

static void clock_setup(void) {
	rcc_clock_setup_hse_3v3(&hse_8mhz_3v3[CLOCK_3V3_168MHZ]);
}

static void gpio_setup(void) {
	rcc_periph_clock_enable(RCC_GPIOA); // Port A is on AHB1
	rcc_periph_clock_enable(RCC_GPIOC); // Port C is on AHB1
	// Set PA4/PA5 for DAC channels to analog, ignoring drive mode
	gpio_mode_setup(GPIOA, GPIO_MODE_ANALOG, GPIO_PUPD_NONE, GPIO4);
	gpio_mode_setup(GPIOA, GPIO_MODE_ANALOG, GPIO_PUPD_NONE, GPIO5);
}

static void timer_setup(void) {
	rcc_periph_clock_enable(RCC_TIM2); // Enable TIM2 clock
	timer_reset(TIM2);
	// Timer global mode: - No divider, Alignment edge, Direction up
	timer_set_mode(TIM2, TIM_CR1_CKD_CK_INT,
		       TIM_CR1_CMS_EDGE, TIM_CR1_DIR_UP);
	timer_continuous_mode(TIM2);
	timer_set_period(TIM2, PERIOD);
	timer_disable_oc_output(TIM2, TIM_OC2 | TIM_OC3 | TIM_OC4);
	timer_enable_oc_output(TIM2, TIM_OC1);
	timer_disable_oc_clear(TIM2, TIM_OC1);
	timer_disable_oc_preload(TIM2, TIM_OC1);
	timer_set_oc_slow_mode(TIM2, TIM_OC1);
	timer_set_oc_mode(TIM2, TIM_OC1, TIM_OCM_TOGGLE);
	timer_set_oc_value(TIM2, TIM_OC1, 500);
	timer_disable_preload(TIM2);
	// Set the timer trigger output (for the DAC) to the channel 1 output compare
        // TODO(aray): just do division instead!
	timer_set_master_mode(TIM2, TIM_CR2_MMS_COMPARE_OC1REF);
	timer_enable_counter(TIM2);
}

static void dma_setup(void) {
	// DACs use DMA1 Channel7 Stream5 (DAC1) and Stream6 (DAC2)
	rcc_periph_clock_enable(RCC_DMA1); // Enable DMA1 clock (both DACs)
	dma_stream_reset(DMA1, DMA_STREAM5);
	dma_stream_reset(DMA1, DMA_STREAM6);
	dma_set_priority(DMA1, DMA_STREAM5, DMA_SxCR_PL_LOW);
	dma_set_priority(DMA1, DMA_STREAM6, DMA_SxCR_PL_LOW);
	dma_set_memory_size(DMA1, DMA_STREAM5, DMA_SxCR_MSIZE_16BIT);
	dma_set_memory_size(DMA1, DMA_STREAM6, DMA_SxCR_MSIZE_16BIT);
	dma_set_peripheral_size(DMA1, DMA_STREAM5, DMA_SxCR_PSIZE_16BIT);
	dma_set_peripheral_size(DMA1, DMA_STREAM6, DMA_SxCR_PSIZE_16BIT);
	dma_enable_memory_increment_mode(DMA1, DMA_STREAM5);
	dma_enable_memory_increment_mode(DMA1, DMA_STREAM6);
	dma_enable_circular_mode(DMA1, DMA_STREAM5);
	dma_enable_circular_mode(DMA1, DMA_STREAM6);
	dma_set_transfer_mode(DMA1, DMA_STREAM5, DMA_SxCR_DIR_MEM_TO_PERIPHERAL);
	dma_set_transfer_mode(DMA1, DMA_STREAM6, DMA_SxCR_DIR_MEM_TO_PERIPHERAL);
	// The target is the DAC 12-bit right justified data register
	dma_set_peripheral_address(DMA1, DMA_STREAM5, (uint32_t) &DAC_DHR12R1);
	dma_set_peripheral_address(DMA1, DMA_STREAM6, (uint32_t) &DAC_DHR12R2);
	// The array v[] is filled with the waveform data to be output
	dma_set_memory_address(DMA1, DMA_STREAM5, (uint32_t) waveform1);
	dma_set_memory_address(DMA1, DMA_STREAM6, (uint32_t) waveform2);
	dma_set_number_of_data(DMA1, DMA_STREAM5, bufsize);
	dma_set_number_of_data(DMA1, DMA_STREAM6, bufsize);
	dma_channel_select(DMA1, DMA_STREAM5, DMA_SxCR_CHSEL_7);
	dma_channel_select(DMA1, DMA_STREAM6, DMA_SxCR_CHSEL_7);
	dma_enable_stream(DMA1, DMA_STREAM5);
	dma_enable_stream(DMA1, DMA_STREAM6);
}

static void dac_setup(void) {
	// Enable the DAC clock on APB1
	rcc_periph_clock_enable(RCC_DAC);
	// Setup the DAC channels 1 & 2, with timer 2 as trigger source.
	// Assume the DAC has woken up by the time the first transfer occurs
	dac_trigger_enable(CHANNEL_1);
	dac_trigger_enable(CHANNEL_2);
	dac_set_trigger_source(DAC_CR_TSEL1_T2);
	dac_set_trigger_source(DAC_CR_TSEL2_T2);
	dac_dma_enable(CHANNEL_1);
	dac_dma_enable(CHANNEL_2);
	dac_enable(CHANNEL_1);
	dac_enable(CHANNEL_2);
}

int main(void) {
	// This is for dual channel 12-bit right aligned
	clock_setup();
	gpio_setup();
	timer_setup();
	dma_setup();
	dac_setup();
	while(1);
	return 0; // We never get here.
}
